# Site settings
title: laguna821
description: laguna821's Portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laguna821.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: 112.jpg
hero-title: 春川, Buffalo, 데이터 사이언스
hero-description: Making sense of big data world from a social scientist's view.

# Author - Creator
author-name: Changhyun Ahn
author-image: 1231.jpg
about-author: I'm a social scientist speciallized in media effects of interactive media.
author-email: laguna821@gmail.com
author-facebook: https://www.facebook.com/changhyun.ahn.7


# Social Media Links (Links are located in hero and footer)
facebook: https://www.facebook.com/changhyun.ahn.7
instagram: https://www.instagram.com/laguna821/

# Contact Form Settings
contact-subtitle: # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: laguna821 # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
